version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-api
    restart: unless-stopped
    environment:
      - PORT=${PORT}
    ports:
      - '5000:5000'
    volumes:
      - ./src:/app/src
    networks:
      - nest-api-network

networks:
  nest-api-network:
    driver: bridge
